"""initial

Revision ID: afac7fe86058
Revises: 
Create Date: 2023-12-28 09:07:26.799165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afac7fe86058'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_results_created_at'), 'calculation_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_calculation_results_expression'), 'calculation_results', ['expression'], unique=False)
    op.create_index(op.f('ix_calculation_results_id'), 'calculation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculation_results_id'), table_name='calculation_results')
    op.drop_index(op.f('ix_calculation_results_expression'), table_name='calculation_results')
    op.drop_index(op.f('ix_calculation_results_created_at'), table_name='calculation_results')
    op.drop_table('calculation_results')
    # ### end Alembic commands ###
